#!/bin/bash

# put our directory in the PATH
OURDIR=$(dirname $(realpath $0))
PATH=$OURDIR:$PATH

source $OURDIR/../env.sh

prepvmforupdate || { echo "Prep failed" >&2; exit 1; }
donewithupdate || { echo "Finalize failed" >&2; exit 1; }
finishvmupdate || { echo "Finish failed" >&2; exit 1; }
